name: CI
on:
  push:
    branches: [master]

jobs:
  chromeWebSecurity-enabled:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start http server
        run: python3 -m http.server &

      - name: Cypress run
        uses: cypress-io/github-action@v2

  chromeWebSecurity-disabled:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start http server
        run: python3 -m http.server &

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config: chromeWebSecurity=false
